version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu1804
install:
  
before_build:
  - nuget restore ZigBeeNet.sln
build:
  verbosity: minimal
  project: ZigBeeNet.sln

test:
  # only assemblies to test
  assemblies:
    - '**\*.test.dll'