version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu1804
install:
  
before_build:
  - nuget restore ZigBeeNet.sln
build:
  verbosity: minimal
  project: ZigBeeNet.sln

deploy:
  provider: NuGet
  api_key:
    secure: tb0vUAnhJVroRFR8vY3YofSxf4F4oym55blGXnTzxzb2HQLaX5BJ79nvL9+z4vMs
  skip_symbols: false
  artifact: /.*\.nupkg/

test:
  # only assemblies to test
  assemblies:
    - '**\*.test.dll'